In [ ]:
# PostrgreSQL, MySQL, SQLServer -> relational databases
# MongoDB, Redis -> No SQL databases

import sqlite3
conn = sqlite3.connect('datafile.db')
cursor = conn.cursor()
print(cursor)

cursor.execute('create table people (id integer primary key, name text, count integer)')
cursor.execute("insert into people (name,count) values ('Bob',1)")
cursor.execute('insert into people (name,count) values (?,?)',("Jill",15))

conn.commit()

# it's more secure to use a ? for each variable and the pass the variables as a tuple parameter to the execute method
# you can also  use variable names prefixed with ":" in the query and pass in a corresponding dictionary with the values to be inserted

cursor.execute("insert into people (name,count) values (:username,:usercount)",{"username":'Joe',"usercount":10})

# after a table is populated you can query the data by using sql commands, again using either ? for variable binding or name and dictionaries

result = cursor.execute("select * from people")
print(result.fetchall())

result = cursor.execute("select * from people where name like :name", {"name":"Bob"})
print(result.fetchall())

cursor.execute("update people set count=? where name=?",(20,"Jill"))
result = cursor.execute("select * from people")
print(result.fetchall())

# fetchone -> get one row of the result
# fetchmany -> return an arbitrary number of rows
# iterating over a file

result = cursor.execute("select * from people")
for row in result:
  print(row)

cursor.execute("update people set count=? where name=?",(40,'Jill'))
conn.commit()
conn.close()

# common sqlite3 database operations
# create a connection to a database -> conn = sqlite3.connect(filename)
# create a cursor for a connection -> cursor = conn.cursor()
# execute a queary with the cursor -> cursor.execute(query)
# return the results of a query -> cursor.fetchall(), cursor.fetchone(), cursor.fetchmany(num_rows)
# commit a transaction to a database -> conn.commit()
# close a connection -> conn.close()

In [ ]:
# to use MySQL, PostrgreSQL and otherrelational databasases u need to have server tha client
# connect on local machine or diffrent machine
# making database handling easier with an object relational mapper
# DjangoORM, SQLAlchemy
# SQL Alchemy
# najpier trzeba zainstalować 'pip install sqlalchemy'
# import components you need to connect to the database and map the table to python objects
from sqlalchemy import(create_engine, select, MetaData, Table, Column, Integer, String)
from sqlalchemy.orm import sessionmaker

# connecting to a database:
dbPath ='datafile2.db'
engine = create_engine('sqlite:///%s' % dbPath) # Creates engine object
metadata = MetaData()
people = Table('people', metadata, # Create 'people' table object
               Column('id',Integer,primary_key=True),
               Column('name',String),
               Column('count',Integer),
               )

Session = sessionmaker(bind=engine) # Create a session
session = Session()
metadata.create_all(engine) # Creates table in database

# inserting some records in SQLAlchemy - many options

#people_ins = people.insert().values(name='Bob',count=1)
#print(str(people_ins))

#session.execute(people_ins)
#session.commit()

# kilka rekordów

#session.execute(people_ins, [
#    {'name':'Jill','count':15},
#    {'name':'Joe','count':10}
#])
#session.commit()
#result = session.execute(select(people))
#for row in result:
#  print(row)

# we can do select operations a bit more directly by instead using the select() method with a, where()
# method to find a particular record

#result = session.execute(select(people).where(people.c.name =='Jill'))
#for row in result:
#  print(row)
# name column -> 'Jill'
# people.c.name -> 'c' name is column, table 'people'

# update() -> for changing values in database
#result = session.execute(people.update().values(count=20).where(people.c.name == "Jill"))
#session.commit()

#result = session.execute(select(people).where(people.c.name == 'Jill'))
#for row in result:
#  print(row)

# MAKING TABLE OBJECTS TO CLASSES
# MAKING A CLASS PEOPLE

from sqlalchemy.orm import declarative_base
Base = declarative_base()
class People(Base):
    __tablename__ = "people"
    id = Column(Integer, primary_key=True)
    name = Column(String)
    count = Column(Integer)

results = session.query(People).filter_by(name='Jill')
for person in results:
    print(person.id, person.name, person.count)

# inserts can be done just by creating and instance of the mapped class and adding it to the session

new_person = People(name='Jane',count=5)
session.add(new_person)
session.commit()
results = session.query(People).all()
for person in results:
  print(person.id,person.name,person.count)

# updating -> retrieving the record u want update, change the values on the mapped instance and put updated record to
# the session to be written back to the database

jill = session.query(People).filter_by(name='Jill').first()
print(jill.name)
jill.count = 22
session.add(jill)
session.commit()
results = session.query(People).all()
for person in results:
  print(person.id,person.name,person.count)

# deleting is similar to updating: you fetch the record to be deleted and then use the sessions, delete() method to delete it

jane = session.query(People).filter_by(name='Jane').first()
session.delete(jane)
session.commit()
jane = session.query(People).filter_by(name="Jane").first()
print(jane)

INSERT INTO people (name, count) VALUES (:name, :count)

NameError: name 'session' is not defined

In [ ]:
# using alembic for database schema changes
# alembic is popular lightweight migration tool for sql alchemy
# install allembic 'pip install alembic'
# then create a generic environment by using 'alembic init alembic'

In [ ]:
# nosql databases
# key value store with redis
# redis is an in networked key-value store
# reis is commonly used for cachong, as an message broker, and for quick lookups of informations
# pip install redi
# trzeba sie zarejestrowac na stronie redisa i ogarnac database

"""Basic connection example.
"""

import redis

r = redis.Redis(
    host='redis-16091.c239.us-east-1-2.ec2.redns.redis-cloud.com',
    port=16091,
    decode_responses=True,
    username="default",
    password="lXMVTXYQb3Z7fBUvXLjUrcNl3eeq38Ir",
)

# print(r.keys())
# r.set('a_key','my value')
# print(r.keys())
# v = r.get('a_key')
# print(v)
# r.incr('counter')
# print(r.get('counter'))
# r.incr('counter')
# print(r.get('counter'))
# print(r.keys())

# example up -> how to set a key wit a value and how to set a key with a 'counter' variable and inrement int
# 'incr' method to add 1 to the urrent value of a key
# the following examples deal with  storing arrays or list
# r.rpush('words','one')
# r.rpush('words','two')
# print(r.lrange('words',0,-1))
# r.rpush('words','three')
# print(r.lrange('words',0,-1))
# print(r.llen('words'))
# r.lpush('words','zero')
# print(r.lrange('words',0,-1))
# print(r.lrange('words',3,3))
# print(r.lindex('words',1))
# print(r.lindex('words',2))

# rpush() -> pushing from the right
# lrange() -> giving the key, both a starting index and an ending index, with -1 idicatory the end of the list
# lpush() -> add to the beginning - left side
# lindex() -> retrieve single value
# llen() -> return length of list

# expiration of values:

# r.setex('timed',10,'10 seconds')
# print(r.pttl('timed'))
# print(r.pttl('timed'))
print(b'timed' in r.keys())
print(r.keys())

# setex() -> ustawia co do usuniecie i ile czasu w sekundach
# pttl() -> pokazuje w milisekundach ile czasu zostalo, -2 to znaczy ze juz zostalo usuniete

In [ ]:
# documents in mongodb
# is sometimes called a document-based atabase because it isn't organized in rows and columns but instead store documents
# a document is stored in a format called BSON (binary json)
# you need to have access to a mongodb server
# free account and instance on mongodb.com
# then you can create a free mongo atlas cluster for experimentation

# be sure to save the username, password and the connection string shown when creating your cluster
# if you want to run mongodb locally, the easies solution is to run a docker instance:
# "docker run -p 27017:27017 mongo"
# pip install pymongo

from pymongo import MongoClient
client = MongoClient(host='mongodb+srv://askkar27:O19Qh84cHvqd2ZMl@cluster0.jucskk0.mongodb.net/')
# testing the client with sample document
import datetime
a_document = {'name':'Jane',
              'age':34,
              'interest':['Python','databases','statistics'],
              'date_added': datetime.datetime.now()}
db = client.my_data # select database wchich hasn't been created yet
collection = db.docs # select a collection in the database, also nt created yet
result = collection.find_one() # searches for first item, no exception even if neither collection or database exist yet
# print(db.list_collection_names())
# to store a document use the  collection isnert_one() method, wchich return the uniqe object id
# print(collection.insert_one(a_document)) ObjectId('6884bd3545a057d80fa25aa2'
# print(collection.find_one())
from bson.objectid import ObjectId
# print(collection.find_one(ObjectId('6884bd3545a057d80fa25aa2')))

# updating
# collection.update_one({'_id': ObjectId('6884bd3545a057d80fa25aa2')}, {"$set": {"name":"Ann"}})
# updates record according to contents of $set object

# replacing with another object
# collection.replace_one({'_id': ObjectId('6884bd3545a057d80fa25aa2')},{'name':'Maria'})
# replaces record with new object, the record is replace with a shorter record

# deleting
# collection.delete_one({'_id': ObjectId('6884bd3545a057d80fa25aa2')})

# even thorugh record has been deleted and the collection is now empty the collection still exists unless it's specifically dropped
# print(db.list_collection_names())
# collection.drop()
print(db.list_collection_names())